Pytest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -130,13 +130,108 @@ jobs:
           format: colored
           strict: false
   test:
-    name: 🚀 Test Package
+    name: 🧪 Test Package
     runs-on: ubuntu-latest
     steps:
       - name: ⤵️ Check out code from GitHub
         uses: actions/checkout@v2.3.4
-      - name: 🏗 Set up Python
-        uses: actions/setup-python@v2
+      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v2.2.1
+        id: python
         with:
           python-version: ${{ env.DEFAULT_PYTHON }}
-          architecture: x64
+      - name: 🏗 Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2.1.4
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements.txt') }}-${{
+            hashFiles('requirements_test.txt') }}
+      - name: 🏗 Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: 🏗 Restore test environment from cache
+        id: cache-precommit
+        uses: actions/cache@v2.1.4
+        with:
+          path: ${{ env.CACHE_TEST_HOME }}
+          key: |
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-test-${{ hashFiles('.test-config.yaml') }}
+      - name: 🏗 Fail job if cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: 🏗 Install Pytest Annotation plugin
+        run: |
+          . venv/bin/activate
+          # Ideally this should be part of our dependencies
+          # However this plugin is fairly new and doesn't run correctly
+          # on a non-GitHub environment.
+          pip install pytest-github-actions-annotate-failures
+      - name: 🧪 Run pytest
+        run: |
+          . venv/bin/activate
+          pip install -r test_requirements.txt
+          pytest \
+            -qq \
+            --timeout=9 \
+            --durations=10 \
+            -n auto \
+            --dist=loadfile \
+            --test-group-count 4 \
+            --test-group=${{ matrix.group }} \
+            --cov homeassistant \
+            -o console_output_style=count \
+            -p no:sugar \
+            tests
+      - name: ⬆ Upload coverage artifact
+        uses: actions/upload-artifact@v2.2.2
+        with:
+          name: coverage-${{ env.DEFAULT_PYTHON }}-group${{ matrix.group }}
+          path: .coverage
+      - name: Check dirty
+        run: |
+          ./script/check_dirty
+  coverage:
+    name: 🏗 Process test coverage
+    runs-on: ubuntu-latest
+    needs: test
+    container: homeassistant/ci-azure:${{ env.DEFAULT_PYTHON }}
+    steps:
+      - name: ⤵️ Check out code from GitHub
+        uses: actions/checkout@v2.3.4
+      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v2.2.1
+        id: python
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: 🏗 Restore full Python ${{ env.DEFAULT_PYTHON }} virtual environment
+        id: cache-venv
+        uses: actions/cache@v2.1.4
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-venv-${{
+            matrix.python-version }}-${{ hashFiles('requirements_test.txt')
+            }}-${{ hashFiles('requirements_all.txt') }}
+      - name: 🏗 Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: ⤵ Download all coverage artifacts
+        uses: actions/download-artifact@v2
+      - name: 🏗 Combine coverage results
+        run: |
+          . venv/bin/activate
+          coverage combine coverage*/.coverage*
+          coverage report --fail-under=94
+          coverage xml
+      - name: ⬆ Upload coverage to Codecov
+        uses: codecov/codecov-action@v1.2.1
